name: Destroy Workflow for dev
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy Dev Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::496113530799:role/tf-lab-github
          aws-region: ap-south-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.3

      - name: Terraform init
        working-directory: ./terraform/environments/dev
        run: terraform init

      - name: Terraform destory
        working-directory: ./terraform/environements/dev
        run: terraform destory -auto-approve
